[project]
name = "androidforge"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Vineet Gaira", email = "vineetgaira1729@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
androidforge = "androidforge:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
